export const KANJI_DATA = [
  // 1. Numbers & Basic Math (15 Kanji)
  { kanji: '一', meaning: 'One', reading: 'ichi' },
  { kanji: '二', meaning: 'Two', reading: 'ni' },
  { kanji: '三', meaning: 'Three', reading: 'san' },
  { kanji: '四', meaning: 'Four', reading: 'yon / shi' },
  { kanji: '五', meaning: 'Five', reading: 'go' },
  { kanji: '六', meaning: 'Six', reading: 'roku' },
  { kanji: '七', meaning: 'Seven', reading: 'shichi / nana' },
  { kanji: '八', meaning: 'Eight', reading: 'hachi' },
  { kanji: '九', meaning: 'Nine', reading: 'kyuu / ku' },
  { kanji: '十', meaning: 'Ten', reading: 'juu' },
  { kanji: '百', meaning: 'Hundred', reading: 'hyaku' },
  { kanji: '千', meaning: 'Thousand', reading: 'sen' },
  { kanji: '万', meaning: 'Ten Thousand', reading: 'man' },
  { kanji: '円', meaning: 'Yen / Circle', reading: 'en / maru' },
  { kanji: '半', meaning: 'Half', reading: 'han / naka(ba)' },

  // 2. Time, Days & Nature (20 Kanji)
  { kanji: '日', meaning: 'Day / Sun', reading: 'nichi / hi' },
  { kanji: '月', meaning: 'Month / Moon', reading: 'getsu / tsuki' },
  { kanji: '火', meaning: 'Fire', reading: 'ka / hi' },
  { kanji: '水', meaning: 'Water', reading: 'sui / mizu' },
  { kanji: '木', meaning: 'Tree', reading: 'moku / ki' },
  { kanji: '金', meaning: 'Gold / Money', reading: 'kin / kane' },
  { kanji: '土', meaning: 'Earth / Soil', reading: 'do / tsuchi' },
  { kanji: '年', meaning: 'Year', reading: 'nen / toshi' },
  { kanji: '時', meaning: 'Time / Hour', reading: 'ji / toki' },
  { kanji: '分', meaning: 'Minute / Understand', reading: 'fun / bun / wa(karu)' },
  { kanji: '午', meaning: 'Noon', reading: 'go' },
  { kanji: '前', meaning: 'Before / Front', reading: 'zen / mae' },
  { kanji: '後', meaning: 'After / Behind', reading: 'go / ushi(ro) / ato' },
  { kanji: '今', meaning: 'Now', reading: 'kon / ima' },
  { kanji: '先', meaning: 'Previous / Ahead', reading: 'sen / saki' },
  { kanji: '来', meaning: 'Next / Come', reading: 'rai / ku(ru)' },
  { kanji: '毎', meaning: 'Every', reading: 'mai' },
  { kanji: '間', meaning: 'Between / Interval', reading: 'kan / aida' },
  { kanji: '天', meaning: 'Heaven', reading: 'ten / ame' },
  { kanji: '気', meaning: 'Spirit / Energy', reading: 'ki' },

  // 3. People & Body Parts (10 Kanji)
  { kanji: '人', meaning: 'Person', reading: 'jin / nin / hito' },
  { kanji: '子', meaning: 'Child', reading: 'shi / ko' },
  { kanji: '女', meaning: 'Woman', reading: 'jo / onna' },
  { kanji: '男', meaning: 'Man', reading: 'dan / nan / otoko' },
  { kanji: '父', meaning: 'Father', reading: 'fu / chichi' },
  { kanji: '母', meaning: 'Mother', reading: 'bo / haha' },
  { kanji: '目', meaning: 'Eye', reading: 'moku / me' },
  { kanji: '耳', meaning: 'Ear', reading: 'ji / mimi' },
  { kanji: '口', meaning: 'Mouth', reading: 'kou / kuchi' },
  { kanji: '手', meaning: 'Hand', reading: 'shu / te' },

  // 4. Directions & Position (10 Kanji)
  { kanji: '上', meaning: 'Up', reading: 'jou / ue' },
  { kanji: '下', meaning: 'Down', reading: 'ka / ge / shita' },
  { kanji: '左', meaning: 'Left', reading: 'sa / hidari' },
  { kanji: '右', meaning: 'Right', reading: 'u / yuu / migi' },
  { kanji: '中', meaning: 'Middle', reading: 'chuu / naka' },
  { kanji: '外', meaning: 'Outside', reading: 'gai / soto' },
  { kanji: '北', meaning: 'North', reading: 'hoku / kita' },
  { kanji: '南', meaning: 'South', reading: 'nan / minami' },
  { kanji: '東', meaning: 'East', reading: 'tou / higashi' },
  { kanji: '西', meaning: 'West', reading: 'sei / nishi' },

  // 5. Common Verbs & Actions (18 Kanji)
  { kanji: '行', meaning: 'Go', reading: 'kou / gyou / i(ku)' },
  { kanji: '来', meaning: 'Come', reading: 'rai / ku(ru)' },
  { kanji: '食', meaning: 'Eat', reading: 'shoku / ta(beru)' },
  { kanji: '飲', meaning: 'Drink', reading: 'in / no(mu)' },
  { kanji: '見', meaning: 'See', reading: 'ken / mi(ru)' },
  { kanji: '聞', meaning: 'Hear / Ask', reading: 'bun / mon / ki(ku)' },
  { kanji: '読', meaning: 'Read', reading: 'doku / yo(mu)' },
  { kanji: '書', meaning: 'Write', reading: 'sho / ka(ku)' },
  { kanji: '話', meaning: 'Speak', reading: 'wa / hana(su)' },
  { kanji: '買', meaning: 'Buy', reading: 'bai / ka(u)' },
  { kanji: '教', meaning: 'Teach', reading: 'kyou / oshi(eru)' },
  { kanji: '休', meaning: 'Rest', reading: 'kyuu / yasu(mu)' },
  { kanji: '出', meaning: 'Exit', reading: 'shutsu / de(ru) / da(su)' },
  { kanji: '入', meaning: 'Enter', reading: 'nyuu / hai(ru) / i(reru)' },
  { kanji: '立', meaning: 'Stand', reading: 'ritsu / ta(tsu)' },
  { kanji: '言', meaning: 'Say', reading: 'gen / gon / i(u)' },
  { kanji: '会', meaning: 'Meet', reading: 'kai / a(u)' },
  { kanji: '住', meaning: 'Live / Reside', reading: 'juu / su(mu)' },

  // 6. Places & Education (15 Kanji)
  { kanji: '山', meaning: 'Mountain', reading: 'san / yama' },
  { kanji: '川', meaning: 'River', reading: 'sen / kawa' },
  { kanji: '田', meaning: 'Rice field', reading: 'den / ta' },
  { kanji: '大', meaning: 'Big', reading: 'dai / tai / oo(kii)' },
  { kanji: '小', meaning: 'Small', reading: 'shou / chii(sai)' },
  { kanji: '高', meaning: 'High / Expensive', reading: 'kou / taka(i)' },
  { kanji: '安', meaning: 'Cheap / Quiet', reading: 'an / yasu(i)' },
  { kanji: '新', meaning: 'New', reading: 'shin / atara(shii)' },
  { kanji: '古', meaning: 'Old', reading: 'ko / furu(i)' },
  { kanji: '多', meaning: 'Many', reading: 'ta / oo(i)' },
  { kanji: '少', meaning: 'Few', reading: 'shou / suko(shi) / suku(nai)' },
  { kanji: '国', meaning: 'Country', reading: 'koku / kuni' },
  { kanji: '校', meaning: 'School', reading: 'kou' },
  { kanji: '学', meaning: 'Study', reading: 'gaku / mana(bu)' },
  { kanji: '生', meaning: 'Life / Student', reading: 'sei / shou / i(kiru) / u(mareru)' },

  // 7. Miscellaneous Essentials (15 Kanji)
  { kanji: '名', meaning: 'Name', reading: 'mei / myou / na' },
  { kanji: '白', meaning: 'White', reading: 'haku / shiro' },
  { kanji: '長', meaning: 'Long / Leader', reading: 'chou / naga(i)' },
  { kanji: '万', meaning: '10,000', reading: 'man / ban' },
  { kanji: '電', meaning: 'Electricity', reading: 'den' },
  { kanji: '車', meaning: 'Car', reading: 'sha / kuruma' },
  { kanji: '語', meaning: 'Language', reading: 'go / kata(ru)' },
  { kanji: '何', meaning: 'What', reading: 'ka / nani / nan' },
  { kanji: '足', meaning: 'Leg / Sufficient', reading: 'soku / ashi / ta(riru)' },
  { kanji: '道', meaning: 'Road', reading: 'dou / michi' },
  { kanji: '金', meaning: 'Gold', reading: 'kin / kane' },
  { kanji: '店', meaning: 'Store', reading: 'ten / mise' },
  { kanji: '社', meaning: 'Company', reading: 'sha / yashiro' },
  { kanji: '方', meaning: 'Direction / Person', reading: 'hou / kata' },
  { kanji: '友', meaning: 'Friend', reading: 'yuu / tomo' },
];
