export const KANJI_DATA = [
  { kanji: '一', meaning: 'One', reading: 'ichi' },
  { kanji: '二', meaning: 'Two', reading: 'ni' },
  { kanji: '三', meaning: 'Three', reading: 'san' },
  { kanji: '四', meaning: 'Four', reading: 'yon / shi' },
  { kanji: '五', meaning: 'Five', reading: 'go' },
  { kanji: '六', meaning: 'Six', reading: 'roku' },
  { kanji: '七', meaning: 'Seven', reading: 'shichi / nana' },
  { kanji: '八', meaning: 'Eight', reading: 'hachi' },
  { kanji: '九', meaning: 'Nine', reading: 'kyuu / ku' },
  { kanji: '十', meaning: 'Ten', reading: 'juu' },
  { kanji: '百', meaning: 'Hundred', reading: 'hyaku' },
  { kanji: '千', meaning: 'Thousand', reading: 'sen' },
  { kanji: '万', meaning: 'Ten Thousand', reading: 'man' },
  { kanji: '円', meaning: 'Yen / Circle', reading: 'en' },
  { kanji: '日', meaning: 'Sun / Day', reading: 'nichi / hi' },
  { kanji: '月', meaning: 'Moon / Month', reading: 'getsu / tsuki' },
  { kanji: '火', meaning: 'Fire', reading: 'ka / hi' },
  { kanji: '水', meaning: 'Water', reading: 'sui / mizu' },
  { kanji: '木', meaning: 'Tree / Wood', reading: 'moku / ki' },
  { kanji: '金', meaning: 'Gold / Money', reading: 'kin / kane' },
  { kanji: '土', meaning: 'Earth / Soil', reading: 'do / tsuchi' },
];
